const fs = require('fs');
const path = require('path');

const structure = {
  'src/config/env.js': `const dotenv = require('dotenv'); dotenv.config();\nmodule.exports = { env: process.env.NODE_ENV || 'development', port: process.env.PORT || 3000, mongoUri: process.env.MONGO_URI, jwt: { secret: process.env.JWT_SECRET, expiresIn: process.env.JWT_EXPIRES_IN || '7d' }, cors: process.env.CORS_ORIGIN || '*', uploadDir: process.env.UPLOAD_DIR || './uploads' };`,
  'src/config/db.js': `const mongoose = require('mongoose');\nconst config = require('./env');\nmodule.exports = async () => { try { await mongoose.connect(config.mongoUri, { dbName: 'startup_db' }); console.log('✅ MongoDB Connected'); } catch (e) { console.error('❌ DB Error:', e); process.exit(1); } };`,
  'src/config/swagger.js': `const swaggerJsdoc = require('swagger-jsdoc');\nconst swaggerUi = require('swagger-ui-express');\nmodule.exports = { swaggerUi, specs: swaggerJsdoc({ definition: { openapi: '3.0.0', info: { title: 'Startup API', version: '1.0.0' }, servers: [{ url: 'http://localhost:3000' }] }, apis: ['./src/routes/*.js'] }) };`,
  'src/utils/appError.js': `class AppError extends Error { constructor(msg, status) { super(msg); this.statusCode = status; this.isOperational = true; } } module.exports = AppError;`,
  'src/utils/catchAsync.js': `module.exports = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);`,
  'src/utils/apiFeatures.js': `class ApiFeatures { constructor(q, qs) { this.q = q; this.qs = qs; }\n  filter() { const obj = {...this.qs}; ['page','sort','limit','fields','keyword'].forEach(k=>delete obj[k]); this.q = this.q.find(JSON.parse(JSON.stringify(obj).replace(/\\b(gte|gt|lte|lt)\\b/g, m=>`+$${m}`))); return this; }\n  sort() { this.q = this.q.sort(this.qs.sort ? this.qs.sort.split(',').join(' ') : '-createdAt'); return this; }\n  limitFields() { this.q = this.q.select(this.qs.fields ? this.qs.fields.split(',').join(' ') : '-__v'); return this; }\n  search(fields) { if(this.qs.keyword) this.q = this.q.find({ $or: fields.map(f=>({[f]: new RegExp(this.qs.keyword,'i')})) }); return this; }\n  paginate() { const p = this.qs.page*1||1, l = this.qs.limit*1||10; this.q = this.q.skip((p-1)*l).limit(l); this.meta = {page:p, limit:l}; return this; }\n}\nmodule.exports = ApiFeatures;`,
  'src/models/User.js': `const mongoose = require('mongoose'); const bcrypt = require('bcryptjs');\nconst s = new mongoose.Schema({ name:{type:String,required:true,trim:true}, email:{type:String,required:true,unique:true,lowercase:true}, password:{type:String,required:true,select:false}, role:{type:String,enum:['user','admin'],default:'user'} },{timestamps:true});\ns.pre('save',async function(n){if(!this.isModified('password'))return n(); this.password=await bcrypt.hash(this.password,12);n();});\ns.methods.comparePassword=async function(c){return bcrypt.compare(c,this.password);};\nmodule.exports = mongoose.model('User', s);`,
  'src/models/Product.js': `const mongoose = require('mongoose');\nmodule.exports = mongoose.model('Product', new mongoose.Schema({ name:{type:String,required:true}, price:{type:Number,required:true}, image:String, createdBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'}, description:String },{timestamps:true}));`,
  'src/services/authService.js': `const jwt=require('jsonwebtoken'); const User=require('../models/User'); const AppError=require('../utils/appError'); const config=require('../config/env');\nconst sign=id=>jwt.sign({id},config.jwt.secret,{expiresIn:config.jwt.expiresIn});\nexports.register=async d=>{if(await User.findOne({email:d.email}))throw new AppError('Email exists',409); const u=await User.create(d); return {user:{id:u._id,name:u.name,email:u.email,role:u.role},token:sign(u._id)};};\nexports.login=async({email,password})=>{const u=await User.findOne({email}).select('+password'); if(!u||!(await u.comparePassword(password)))throw new AppError('Invalid',401); return {user:{id:u._id,name:u.name,email:u.email,role:u.role},token:sign(u._id)};};`,
  'src/services/genericService.js': `const ApiFeatures=require('../utils/apiFeatures');\nmodule.exports = {\n  create: M=>d=>M.create(d),\n  getOne: M=>(id,p)=>M.findById(id).populate(p),\n  getAll: M=>(q,p)=>{const f=new ApiFeatures(M.find(),q).filter().sort().limitFields().search(['name','description']).paginate(); return {docs:f.q.populate(p),meta:f.meta};},\n  update: M=>(id,d)=>M.findByIdAndUpdate(id,d,{new:true,runValidators:true}),\n  delete: M=>id=>M.findByIdAndDelete(id)\n};`,
  'src/controllers/authController.js': `const {register,login}=require('../services/authService'); const catchAsync=require('../utils/catchAsync');\nexports.signup=catchAsync(async(r,res)=>res.status(201).json({status:'success',data:await register(r.body)}));\nexports.login=catchAsync(async(r,res)=>res.status(200).json({status:'success',data:await login(r.body)}));`,
  'src/controllers/genericController.js': `const gs=require('../services/genericService'); module.exports=M=>({\n  create: async(r,res)=>{res.status(201).json({status:'success',data:await gs.create(M)(r.body)});},\n  getAll: async(r,res)=>{const{docs,meta}=await gs.getAll(M)(r.query,r.populateOptions);res.json({status:'success',results:docs.length,meta,data:docs});},\n  getOne: async(r,res)=>res.json({status:'success',data:await gs.getOne(M)(r.params.id,r.populateOptions)}),\n  update: async(r,res)=>res.json({status:'success',data:await gs.update(M)(r.params.id,r.body)}),\n  delete: async(r,res)=>{await gs.delete(M)(r.params.id);res.status(204).json({status:'success'});}\n});`,
  'src/middleware/auth.js': `const jwt=require('jsonwebtoken'); const User=require('../models/User'); const AppError=require('../utils/appError'); const config=require('../config/env');\nexports.protect=async(r,res,next)=>{const t=r.headers.authorization?.startsWith('Bearer ')?r.headers.authorization.split(' ')[1]:null; if(!t)return next(new AppError('Login required',401)); try{const d=jwt.verify(t,config.jwt.secret); const u=await User.findById(d.id); if(!u)return next(new AppError('Invalid',401)); r.user=u;next();}catch{next(new AppError('Invalid token',401));}};\nexports.restrictTo=(...roles)=>(r,res,next)=>roles.includes(r.user.role)?next():next(new AppError('Forbidden',403));`,
  'src/middleware/validator.js': `const {ZodError}=require('zod'); module.exports=s=>(r,res,next)=>{try{s.parse(r.body);next();}catch(e){if(e instanceof ZodError)return res.status(400).json({status:'fail',errors:e.errors.map(x=>x.path.join('.')+': '+x.message)});next(e);}};`,
  'src/middleware/upload.js': `const multer=require('multer'); const path=require('path'); const config=require('../config/env');\nconst storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,config.uploadDir),filename:(r,f,cb)=>cb(null,Date.now()+'-'+Math.round(Math.random()*1E9)+path.extname(f.originalname))});\nmodule.exports=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/jpeg|jpg|png|pdf|docx/.test(path.extname(f.originalname).toLowerCase()))});`,
  'src/middleware/errorHandler.js': `const AppError=require('../utils/appError'); module.exports=(err,r,res,next)=>{err.statusCode=err.statusCode||500; err.status=err.status||'error'; res.status(err.statusCode).json({status:err.status,message:err.message,stack:process.env.NODE_ENV==='development'?err.stack:undefined});};`,
  'src/middleware/logger.js': `const winston=require('winston'); module.exports=winston.createLogger({level:'info',format:winston.format.combine(winston.format.timestamp(),winston.format.json()),transports:[new winston.transports.Console(),new winston.transports.File({filename:'logs/error.log',level:'error'}),new winston.transports.File({filename:'logs/combined.log'})]});`,
  'src/routes/auth.routes.js': `const express=require('express'); const {signup,login}=require('../controllers/authController'); const router=express.Router(); router.post('/signup',signup); router.post('/login',login); module.exports=router;`,
  'src/routes/index.routes.js': `const express=require('express'); const router=express.Router(); const auth=require('./auth.routes'); const createRes=require('../controllers/genericController'); const Product=require('../models/Product'); const upload=require('../middleware/upload'); const {protect,restrictTo}=require('../middleware/auth'); const {validate}=require('../middleware/validator'); const {z}=require('zod');\nconst prod=createRes(Product);\nrouter.use('/auth',auth);\nrouter.get('/products',prod.getAll);\nrouter.get('/products/:id',prod.getOne);\nrouter.post('/products',protect,upload.single('image'),validate(z.object({name:z.string().min(3),price:z.number().positive()})),(r,res,next)=>{r.body.image=r.file?.path;r.body.createdBy=r.user.id;next();},prod.create);\nrouter.put('/products/:id',protect,prod.update);\nrouter.delete('/products/:id',protect,restrictTo('admin'),prod.delete);\nmodule.exports=router;`,
  'src/app.js': `const express=require('express'); const helmet=require('helmet'); const cors=require('cors'); const rateLimit=require('express-rate-limit'); const morgan=require('morgan'); const routes=require('./routes'); const {swaggerUi,specs}=require('./config/swagger'); const config=require('./config/env'); const errorHandler=require('./middleware/errorHandler'); const AppError=require('./utils/appError');\nconst app=express(); app.use(helmet()); app.use(cors({origin:config.cors,credentials:true})); app.use(rateLimit({windowMs:15*60*1000,max:100})); app.use(express.json({limit:'10kb'})); app.use(morgan('dev')); app.use('/uploads',express.static(config.uploadDir)); app.use('/api-docs',swaggerUi.serve,swaggerUi.setup(specs)); app.use('/api',routes); app.all('*',(r,res,next)=>next(new AppError(\`Route \${r.originalUrl} not found\`,404))); app.use(errorHandler); module.exports=app;`,
  'server.js': `require('dotenv').config(); const app=require('./src/app'); const connectDB=require('./src/config/db'); const config=require('./src/config/env');\nconst start=async()=>{await connectDB(); app.listen(config.port,()=>console.log(\`🚀 Running on http://localhost:\${config.port} [\${config.env}]\`));}; start();\nprocess.on('SIGTERM',()=>process.exit(0)); process.on('SIGINT',()=>process.exit(0));`,
  '.env.example': `NODE_ENV=development\nPORT=3000\nMONGO_URI=mongodb://localhost:27017/startup_db\nJWT_SECRET=your_super_secret\nCORS_ORIGIN=http://localhost:5173\nUPLOAD_DIR=./uploads`,
  'package.json': `{\n  "name": "startup-backend",\n  "version": "1.0.0",\n  "scripts": {"dev":"nodemon server.js","start":"node server.js"},\n  "dependencies": {"express":"^4.18.2","mongoose":"^8.0.0","dotenv":"^16.3.1","bcryptjs":"^2.4.3","jsonwebtoken":"^9.0.2","zod":"^3.22.4","helmet":"^7.1.0","cors":"^2.8.5","express-rate-limit":"^7.1.4","multer":"^1.4.5-lts.1","winston":"^3.11.0","swagger-jsdoc":"^6.2.8","swagger-ui-express":"^5.0.0","morgan":"^1.10.0"},\n  "devDependencies": {"nodemon":"^3.0.2"}\n}`
};

Object.entries(structure).forEach(([file, content]) => {
  const dir = path.dirname(file);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, content);
  console.log(`✅ Created: ${file}`);
});
console.log('\n🎉 Project scaffolded! Run: npm install && npm run dev');
